# ruff: noqa: D103

"""End-to-end accuracy checks for the :py:class:`CorrelatedObservation` resampling paths.

Run with ``pytest -s tests/scarlet2/test_correlated_observation.py`` to see the printed
calibration table.

Each check builds a noise model from blank sky, then evaluates the reduced chi^2 over
many noise realizations, for:

* **hi-res**: ``from_observation`` -- correlation function -> power spectrum, no resampling
* **lo-res**: ``from_resampling(..., compute_power_spectrum=True)`` -- a low-resolution observation
  upsampled onto the finer model grid, generative power spectrum
* **joint**: both together
* **delivered pre-resampled**: data that arrived already resampled onto a finer grid, so only
  ``from_observation`` is available -- with and without the ``native_scale`` hint

For every path we report two numbers:

* ``chi2 / n_eff`` -- normalized by the effective number of degrees of freedom
  (:py:attr:`CorrelatedObservation.n_eff`)
* ``chi2 / n_pix`` -- normalized by the raw pixel count

and each is measured for a residual that is exactly the modeled noise (*pure noise*,
isolating the noise-model estimator) and for data generated by the honest slow forward
model of a true scene (*with source*, which adds the fast renderer's approximation
error -- for the resampled path, the non-commutation of convolution and resampling above
the original Nyquist).

What these numbers show (as of writing):

* the correlation-function path is well calibrated (``chi2 / n_eff`` ~ 1.0) for realistic
  short-range pixel correlations. It is *not* for a smooth, high-dynamic-range noise
  spectrum, which a lag-truncated tapered correlation function cannot represent.
* the fast renderer of the resampled path reproduces the slow forward model to well
  within the noise: the *with source* and *pure noise* numbers are essentially equal, so
  the convolution/resampling non-commutation has negligible practical effect here.
* upsampling makes the noise covariance rank-deficient. ``_chisquare`` masks out the modes
  above the original Nyquist (they hold only resampling leakage), and ``n_eff`` counts the
  informative modes, so ``chi2 / n_eff`` ~ 1.0 for pure noise. ``chi2 / n_pix`` stays well
  below 1 because most pixels are not independent.
"""

import equinox as eqx
import jax.numpy as jnp
import numpy as np
import pytest

from scarlet2 import CorrelatedObservation, Frame, GaussianPSF, Observation
from scarlet2.bbox import Box
from scarlet2.fft import convolve
from scarlet2.frame import _wcs_default
from scarlet2.renderer import LanczosResamplingTranformation
from scarlet2.validation_utils import set_validation

NF = 72  # fine (model) grid
NC = 48  # coarse (low-res observation) grid  ->  1.5x upsampling
SIG = 1.0  # per-pixel noise level
N_MODEL = 16  # realizations for the resampled power-spectrum estimate
N_CAL = 16  # realizations for the calibration measurement
SEED = 12345
LANCZOS = 9  # matches CorrelatedObservation.from_resampling default

# realistic drizzle-like pixel correlation: sharp core, weak nearest/diagonal neighbors
CORR_KERNEL = np.array([[0.10, 0.25, 0.10], [0.25, 1.00, 0.25], [0.10, 0.25, 0.10]])


@pytest.fixture(autouse=True)
def _no_validation():
    set_validation(False)


def _gauss(shape, sigma):
    yy, xx = np.indices(shape).astype(float)
    yy -= shape[0] // 2
    xx -= shape[1] // 2
    g = np.exp(-(yy**2 + xx**2) / (2 * sigma**2))
    return g / g.sum()


def _pconv(img, kernel):
    """Periodic convolution of ``img`` with a centered ``kernel`` of any (smaller) size."""
    k = np.zeros_like(img)
    kh, kw = kernel.shape
    k[:kh, :kw] = kernel
    k = np.roll(k, (-(kh // 2), -(kw // 2)), axis=(0, 1))
    return np.fft.irfft2(np.fft.rfft2(img) * np.fft.rfft2(k), s=img.shape)


def _corr_noise(rng):
    """White noise turned into a unit-variance correlated field (kernel is L2-normalized)."""
    k = CORR_KERNEL / np.sqrt((CORR_KERNEL**2).sum())
    return _pconv(rng.standard_normal((NF, NF)), k)


def _lanczos(src_frame, dst_frame):
    """A psf-free Lanczos resampler, built exactly like the one inside ``from_resampling``."""
    src = Frame(src_frame.bbox, psf=None, wcs=src_frame.wcs, channels=src_frame.channels)
    box = src_frame.bbox[:-2] @ dst_frame.bbox.spatial
    dst = Frame(box, psf=None, wcs=dst_frame.wcs, channels=src_frame.channels)
    return LanczosResamplingTranformation(src, dst, lanczos_order=LANCZOS)


def _reduced_chi2(co, data_list, model):
    """chi^2 for each data realization, reusing ``co``'s noise model. Returns chi^2 (not reduced)."""
    out = []
    for data in data_list:
        co_i = eqx.tree_at(lambda o: o.data, co, jnp.asarray(data, dtype=float))
        co_i._match_power_spectrum()  # refresh cached padded spectrum / data FFT for the new data
        out.append(float(co_i.goodness_of_fit(model)) * co.n_eff)
    return np.array(out)


def _report(name, n_eff, n_pix, pure, with_source):
    def line(chi2):
        return (
            f"chi2/n_eff = {chi2.mean() / n_eff:5.3f} +- {chi2.std(ddof=1) / np.sqrt(len(chi2)) / n_eff:.3f}"
            f"   chi2/n_pix = {chi2.mean() / n_pix:5.3f}"
        )

    print(
        f"\n{name}"
        f"\n  n_eff = {n_eff}   n_pix = {n_pix}"
        f"\n  pure noise  : {line(pure)}"
        f"\n  with source : {line(with_source)}"
    )


@pytest.fixture(scope="module")
def paths():
    set_validation(False)
    rng = np.random.default_rng(SEED)

    wcs_f = _wcs_default((NF, NF))
    wcs_c = _wcs_default((NC, NC))
    wcs_c.wcs.cdelt = [c * NF / NC for c in wcs_f.wcs.cdelt]

    model_psf = GaussianPSF(0.8)
    hi_psf = GaussianPSF(1.5)  # fine-instrument PSF, in fine pixels
    lo_psf = GaussianPSF(1.3)  # coarse-instrument PSF, in coarse pixels

    model_frame = Frame(Box((1, NF, NF)), psf=model_psf, wcs=wcs_f, channels=["v"])

    # true scene: a smooth blob plus a compact feature carrying power near/above the coarse Nyquist
    profile = jnp.asarray(220.0 * _gauss((NF, NF), 3.5) + 90.0 * _gauss((NF, NF), 1.0))
    truth = convolve(profile, model_psf(), axes=(-2, -1))[None]  # model-frame image, (1, NF, NF)

    # --- hi-res: correlation-function -> power-spectrum path ---
    hi_blank = Observation(
        (SIG * _corr_noise(rng))[None],
        weights=jnp.full((1, NF, NF), 1 / SIG**2),
        psf=hi_psf,
        wcs=wcs_f,
        channels=["v"],
    )
    hi_corr = CorrelatedObservation.from_observation(hi_blank, patch_size=NF, maxlength=12)
    hi_corr.match(model_frame)
    hi_signal = np.asarray(convolve(profile, hi_psf(), axes=(-2, -1))[None])  # honest hi-res data

    # --- lo-res: resampled generative power-spectrum path (upsampling) ---
    lo_blank = Observation(
        (SIG * rng.standard_normal((NC, NC)))[None],
        weights=jnp.full((1, NC, NC), 1 / SIG**2),
        psf=lo_psf,
        wcs=wcs_c,
        channels=["v"],
    )
    lo_corr = CorrelatedObservation.from_resampling(
        lo_blank, model_frame, resample_psf=True, compute_power_spectrum=True, n_realizations=N_MODEL
    )
    lo_corr.match(model_frame)

    # exact upsampler that from_observation used internally, and its downsampling counterpart
    up = _lanczos(lo_blank.frame, model_frame)
    down = _lanczos(model_frame, lo_blank.frame)
    # honest slow low-res forward model of the truth: convolve with the coarse PSF (in fine pixels),
    # then resample down. `up(ref_lo + noise)` is the data the resampled path actually sees.
    lo_psf_fine = _gauss((NF, NF), 1.3 * NF / NC)
    ref_lo = np.asarray(down(jnp.asarray(_pconv(np.asarray(profile), lo_psf_fine)[None])))

    return {
        "truth": truth,
        "hi_corr": hi_corr,
        "hi_signal": hi_signal,
        "lo_corr": lo_corr,
        "ref_lo": ref_lo,
        "up": up,
        "n_pix": NF * NF,
        "model_frame": model_frame,
        "native_scale": (wcs_c.proj_plane_pixel_scales()[0] * wcs_c.proj_plane_pixel_scales()[1]) ** 0.5,
    }


def test_hires_correlation_function_path(paths):
    p = paths
    rng = np.random.default_rng(SEED + 1)
    noise = [SIG * _corr_noise(rng) for _ in range(N_CAL)]

    pure = _reduced_chi2(p["hi_corr"], [n[None] for n in noise], jnp.zeros_like(p["truth"]))
    with_source = _reduced_chi2(p["hi_corr"], [p["hi_signal"] + n[None] for n in noise], p["truth"])
    n_eff = p["hi_corr"].n_eff
    _report("hi-res  (correlation function -> power spectrum)", n_eff, p["n_pix"], pure, with_source)

    # realistic short-range correlations: this path is well calibrated and full rank
    assert 0.8 < pure.mean() / n_eff < 1.25
    # no resampling, so adding a source barely moves the calibration
    assert abs(with_source.mean() - pure.mean()) / n_eff < 0.3


def test_resampled_lowres_power_spectrum_path(paths):
    p = paths
    rng = np.random.default_rng(SEED + 2)
    whites = [SIG * rng.standard_normal((1, NC, NC)) for _ in range(N_CAL)]
    up = p["up"]

    pure_data = [np.asarray(up(jnp.asarray(w))) for w in whites]
    src_data = [np.asarray(up(jnp.asarray(p["ref_lo"] + w))) for w in whites]

    pure = _reduced_chi2(p["lo_corr"], pure_data, jnp.zeros_like(p["truth"]))
    with_source = _reduced_chi2(p["lo_corr"], src_data, p["truth"])
    n_eff = p["lo_corr"].n_eff
    _report("lo-res  (resampled power spectrum, resample_psf=True)", n_eff, p["n_pix"], pure, with_source)

    # _chisquare masks out the rank-deficient surplus band, so chi2/n_eff is calibrated to ~1
    assert 0.85 < pure.mean() / n_eff < 1.2
    assert pure.mean() / p["n_pix"] < 0.75  # ... while chi2/n_pix stays diluted (most pixels dependent)
    # the fast renderer matches the slow forward model: adding a source must not move the calibration
    assert abs(with_source.mean() - pure.mean()) / n_eff < 0.1


def test_joint(paths):
    p = paths
    rng = np.random.default_rng(SEED + 3)
    hi_noise = [SIG * _corr_noise(rng) for _ in range(N_CAL)]
    whites = [SIG * rng.standard_normal((1, NC, NC)) for _ in range(N_CAL)]
    up = p["up"]

    hi_data = [p["hi_signal"] + n[None] for n in hi_noise]
    lo_data = [np.asarray(up(jnp.asarray(p["ref_lo"] + w))) for w in whites]

    ne_h = p["hi_corr"].n_eff
    ne_l = p["lo_corr"].n_eff
    chi2_h = _reduced_chi2(p["hi_corr"], hi_data, p["truth"])
    chi2_l = _reduced_chi2(p["lo_corr"], lo_data, p["truth"])
    joint = (chi2_h + chi2_l) / (ne_h + ne_l)
    print(
        f"\njoint   (hi-res + lo-res)"
        f"\n  n_eff = {ne_h + ne_l}"
        f"\n  reduced chi2 = {joint.mean():.3f} +- {joint.std(ddof=1) / np.sqrt(len(joint)):.3f}"
    )

    assert 0.5 < joint.mean() < 3.0


def test_delivered_pre_resampled(paths):
    """Data that reached us already resampled onto a finer grid: only the correlation-function path is
    available, and it needs `native_scale` to recover the true number of degrees of freedom."""
    p = paths
    mf = p["model_frame"]
    rng = np.random.default_rng(SEED + 4)
    up = p["up"]
    resample = lambda: np.asarray(up(jnp.asarray(rng.standard_normal((1, NC, NC)))))
    sig = float(np.std([resample() for _ in range(4)]))

    def delivered_obs():
        return Observation(
            resample()[0][None],
            weights=jnp.full((1, NF, NF), 1 / sig**2),
            psf=GaussianPSF(1.5),
            wcs=mf.wcs,
            channels=["v"],
        )

    z = jnp.zeros((1, NF, NF))

    # without native_scale: treated as full rank, chi^2 sums leakage modes -> wildly miscalibrated
    co_naive = CorrelatedObservation.from_observation(delivered_obs(), patch_size=NF, maxlength=12)
    co_naive.match(mf)
    naive = _reduced_chi2(co_naive, [resample() for _ in range(4)], z)

    # with native_scale: rank-deficient handling kicks in
    co = CorrelatedObservation.from_observation(
        delivered_obs(), patch_size=NF, maxlength=12, native_scale=p["native_scale"]
    )
    co.match(mf)
    good = _reduced_chi2(co, [resample() for _ in range(N_CAL)], z)

    print(
        f"\ndelivered pre-resampled (correlation function only)"
        f"\n  n_eff:  naive = {co_naive.n_eff}   with native_scale = {co.n_eff}"
        f"\n  reduced chi2:  naive = {naive.mean() / co_naive.n_eff:.2f}"
        f"   with native_scale = {good.mean() / co.n_eff:.3f} +- {good.std(ddof=1) / np.sqrt(len(good)) / co.n_eff:.3f}"
    )

    assert co.n_eff < co_naive.n_eff  # native_scale reduced the DOF count
    assert co._mode_mask is not None
    assert naive.mean() / co_naive.n_eff > 5.0  # naive is badly off
    assert 0.8 < good.mean() / co.n_eff < 1.3  # native_scale restores calibration


def test_from_resampling_masks_sources(paths):
    """`from_resampling` must exclude bright celestial sources from the correlation measurement, using
    the resampled noise level (not resampled weights) for the 3-sigma cut."""
    p = paths
    mf = p["model_frame"]
    up = p["up"]
    rng = np.random.default_rng(SEED + 5)

    wcs_c = _wcs_default((NC, NC))
    wcs_c.wcs.cdelt = [c * NF / NC for c in mf.wcs.wcs.cdelt]

    yy, xx = np.indices((NC, NC)).astype(float)
    source = 40.0 * np.exp(-((yy - NC / 2) ** 2 + (xx - NC / 2) ** 2) / (2 * 3.0**2))  # 40-sigma peak

    def coarse_obs(with_source):
        data = (source if with_source else 0.0) + SIG * rng.standard_normal((NC, NC))
        return Observation(
            data[None],
            weights=jnp.full((1, NC, NC), 1 / SIG**2),
            psf=GaussianPSF(1.3),
            wcs=wcs_c,
            channels=["v"],
        )

    z = jnp.zeros((1, NF, NF))

    co_src = CorrelatedObservation.from_resampling(
        coarse_obs(True), mf, resample_psf=True, patch_size=48, maxlength=10
    )
    co_src.match(mf)

    out = []
    for _ in range(8):
        d = np.asarray(up(jnp.asarray(SIG * rng.standard_normal((1, NC, NC)))))
        co_i = eqx.tree_at(lambda o: o.data, co_src, jnp.asarray(d))
        co_i._match_power_spectrum()
        out.append(float(co_i.goodness_of_fit(z)))
    c_src = float(np.mean(out))
    xi00 = float(np.asarray(jnp.fft.irfft2(co_src.power_spectrum, s=(NF, NF))[..., 0, 0]).ravel()[0])
    print(f"\nfrom_resampling source masking:  chi2/n_eff = {c_src:.3f}   per-pixel variance = {xi00:.3f}")

    # a 40-sigma source leaking into the correlation function would blow up the per-pixel variance
    # (should be ~ resampled sigma^2, well below 1) and collapse chi2/n_eff far below 1.
    assert xi00 < 0.5
    assert 0.7 < c_src < 1.4
